/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x94, 0x88, 0xC9, 0x1C, 0x01, 0x8F, 0x64, 0xFC}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 5 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 8 }

#define DYNAMIC_KEYMAP_MACRO_COUNT 32
#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2

#undef SERIAL_NUMBER
#define SERIAL_NUMBER DEF_SERIAL_NUMBER ":vial:f64c2b3c"
